DWAPlannerROS:
    max_vel_x: 0.4
    min_vel_x: -0.2
    max_vel_theta: 0.4

    acc_lim_th: 1.5
    acc_lim_x: 1.5
    
    yaw_goal_tolerance: 0.1
    xy_goal_tolerance: 0.1

    holonomic_robot: false

    path_distance_bias: 50.0