stretch_controller_raw:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - joint_head_pan
    - joint_head_tilt
    - joint_lift
    - joint_arm_l3
    - joint_arm_l2
    - joint_arm_l1
    - joint_arm_l0
    - joint_wrist_yaw
    - joint_gripper_finger_right
    - joint_gripper_finger_left
  allow_partial_joints_goal: true

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05

    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10


  gains:
    joint_head_pan: {p: 10, d: 1, i: 0, i_clamp: 1}
    joint_head_tilt: {p: 10, d: 1, i: 0, i_clamp: 1}
    joint_lift: {p: 500, d: 100, i: 0, i_clamp: 1}
    joint_arm_l3: {p: 100, d: 30, i: 0, i_clamp: 1}
    joint_arm_l2: {p: 100, d: 30, i: 0, i_clamp: 1}
    joint_arm_l1: {p: 100, d: 30, i: 0, i_clamp: 1}
    joint_arm_l0: {p: 100, d: 30, i: 0, i_clamp: 1}
    joint_wrist_yaw: {p: 100, d: 1, i: 0, i_clamp: 1}
    joint_gripper_finger_right: {p: 100, d: 1, i: 0, i_clamp: 1}
    joint_gripper_finger_left: {p: 100, d: 1, i: 0, i_clamp: 1}