stretch_gripper_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - joint_gripper_finger_right
    - joint_gripper_finger_left
  allow_partial_joints_goal: true

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_gripper_finger_right: {trajectory: 0.1, goal: 0.1}
    joint_gripper_finger_left: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  gains:
    joint_gripper_finger_right: {p: 100, d: 1, i: 0, i_clamp: 1}
    joint_gripper_finger_left: {p: 100, d: 1, i: 0, i_clamp: 1}
