#!/usr/bin/env python

from std_srvs.srv import Empty
import rospy
import time

rospy.init_node('unpause_after_wait')
rospy.wait_for_service('/gazebo/unpause_physics')
unpause_physics = rospy.ServiceProxy('/gazebo/unpause_physics', Empty)

time.sleep(4.0)
unpause_physics()
rospy.loginfo("Physics unpaused")