#!/usr/bin/env python3
import sys

from rqt_gui.main import Main


def main():
    sys.exit(Main().main(sys.argv, standalone='stretch_dashboard.stretch_dashboard.StretchDashboard'))


if __name__ == '__main__':
    main()
